resources:
- namespaces.yaml
- serviceaccounts.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.5.3
  releaseName: my-cert-manager
  namespace: cert-manager
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 15.9.0
  releaseName: prometheus
  namespace: prometheus